app_name: "IDXR Production"
app_version: "2.1.0"
environment: "production"
debug: false
demo_mode: false
host: "0.0.0.0"
port: 3000
workers: 4
reload: false

database:
  host: "${DB_HOST}"
  port: ${DB_PORT}
  database: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  pool_size: 50
  max_overflow: 100
  pool_timeout: 30
  pool_recycle: 3600
  echo: false
  ssl_mode: "require"

redis:
  host: "${REDIS_HOST}"
  port: ${REDIS_PORT}
  database: 0
  password: "${REDIS_PASSWORD}"
  ssl: true
  connection_pool_size: 20

security:
  jwt_secret_key: "${JWT_SECRET_KEY}"
  jwt_expire_hours: 8
  password_min_length: 12
  password_require_uppercase: true
  password_require_lowercase: true
  password_require_numbers: true
  password_require_special: true
  max_login_attempts: 3
  lockout_duration_minutes: 30
  cors_origins: ["https://idxr.colorado.gov", "https://admin.idxr.colorado.gov"]
  cors_credentials: true
  rate_limit_enabled: true
  security_headers: true

matching:
  enabled_algorithms: ["deterministic", "probabilistic", "ai_hybrid", "fuzzy"]
  default_confidence_threshold: 0.85
  auto_match_threshold: 0.95
  manual_review_threshold: 0.70
  batch_size: 1000
  max_matches_returned: 10
  enable_caching: true
  cache_ttl_seconds: 300
  enable_ml_enhancement: true
  ml_model_path: "/app/models/identity_matcher_v2.1.pkl"
  fuzzy_max_distance: 3
  soundex_enabled: true
  metaphone_enabled: true
  jaro_winkler_threshold: 0.85
  deterministic_weight: 0.4
  probabilistic_weight: 0.3
  ai_hybrid_weight: 0.2
  fuzzy_weight: 0.1
  twins_detection_enabled: true
  children_handling_enabled: true
  homeless_population_handling: true
  data_anomaly_detection: true

monitoring:
  prometheus_enabled: true
  prometheus_port: 9090
  metrics_collection_interval: 30
  health_check_enabled: true
  health_check_interval: 60
  distributed_tracing_enabled: true
  log_level: "INFO"
  log_format: "json"
  log_file: "/var/log/idxr/application.log"
  max_log_file_size: 100
  log_retention_days: 30
  alert_webhook_url: "${ALERT_WEBHOOK_URL}"
  alert_thresholds:
    cpu_usage:
      warning: 75.0
      critical: 90.0
    memory_usage:
      warning: 80.0
      critical: 95.0
    disk_usage:
      warning: 85.0
      critical: 95.0
    response_time:
      warning: 1000.0
      critical: 5000.0
    error_rate:
      warning: 1.0
      critical: 5.0

features:
  advanced_matching: true
  household_detection: true
  real_time_processing: true
  data_quality_checks: true
  comprehensive_reporting: true
  admin_interface: true
  api_rate_limiting: true
  security_monitoring: true
  compliance_tracking: true

external_services:
  address_validation:
    enabled: true
    provider: "usps"
    api_key: "${USPS_API_KEY}"
    timeout: 30
  phone_validation:
    enabled: true
    provider: "twilio"
    api_key: "${TWILIO_API_KEY}"
    timeout: 10
  email_validation:
    enabled: true
    provider: "sendgrid"
    api_key: "${SENDGRID_API_KEY}"
    timeout: 10